data_dir : "D:/Notebook_workdir/thesis/data"

object_type: 'cls'
reg_columns : ["FeH", "CH", "Teff", "logg", "CFe"]
cls_columns: ['f_CEMP']
cls_dict: {0: 'MP', 1: 'CEMP', 2: 'NMP'}


y_mean : [-8.81020067e-01, -9.78005818e-01, 4.91095684e+03, 2.55795385e+00, -9.69857512e-02]
y_std : [7.61077821e-01, 8.42965361e-01, 4.97515564e+02, 1.15882902e+00, 3.06636238e-01]



object_name: 'BGANet_cls'

resume_from : 'D:/Notebook_workdir/thesis/model_save/BGANet_reg/best.pth'

lr: 0.0001
loss: 
  cls_loss:
    loss_name: 'CrossEntropyLoss'
    rate: 1
  
model: 
  name: 'BGANet'
  len_spectrum: 4900
model: 
  name: 'BGANet'
  len_spectrum: 4900