object_type: 'cls'

object_name: 'MPBD_cls_aug'
data_dir : "D:/Notebook_workdir/thesis/data"
model: 
  name: 'MPBDNet'
  list_inplanes: [20,40,80,160]
  len_spectrum: 4900

reg_columns : ["FeH", "CH", "Teff", "logg", "CFe"]
cls_columns: ['f_CEMP']
cls_dict: {0: 'MP', 1: 'CEMP', 2: 'NMP'}
num_classes: 3

y_mean : [-8.81020067e-01, -9.78005818e-01, 4.91095684e+03, 2.55795385e+00, -9.69857512e-02]
y_std : [7.61077821e-01, 8.42965361e-01, 4.97515564e+02, 1.15882902e+00, 3.06636238e-01]

lr: 0.0001

loss: 
  cls_loss:
    loss_name: 'CrossEntropyLoss'
    rate: 1

scheduler:
  name: 'StepLR'
  step_size: 30
  gamma: 0.75

resume_from : 'D:/Notebook_workdir/thesis/model_save/MPBD_cls/best.pth'

# 数据增强配置
data_augmentation:
  probability: 0.6  # 整体增强概率，60%的样本会被增强
  methods:
    # 高斯噪声：模拟仪器噪声
    gaussian_noise:
      enabled: True
      probability: 0.4
      std: 0.008  # 噪声标准差，相对保守
      
    # 光谱缩放：模拟仪器响应差异
    spectral_scaling:
      enabled: True
      probability: 0.3
      range: 0.08  # ±8%的缩放范围
      
    # 基线漂移：模拟观测条件变化
    baseline_drift:
      enabled: True
      probability: 0.35
      strength: 0.015  # 漂移强度
      
    # 波长轴偏移：模拟光谱校准误差
    wavelength_shift:
      enabled: True
      probability: 0.25
      max_shift: 3  # 最大偏移3个像素点
      
    # 光谱平滑：模拟不同分辨率
    spectral_smooth:
      enabled: False  # 可选，可能会损失特征
      probability: 0.2
      kernel_size: 3
      
    # 光谱dropout：模拟部分波段缺失
    spectral_dropout:
      enabled: False  # 谨慎使用，可能影响关键特征
      probability: 0.05 