data_dir : "D:/Notebook_workdir/thesis/data"

object_type: 'cls'
mode: raw
reg_columns : ["FeH", "CH", "Teff", "logg", "CFe"]
cls_columns: ['f_CEMP']
cls_dict: {0: 'MP', 1: 'CEMP', 2: 'NMP'}
num_classes: 3

y_mean : [-8.81020067e-01, -9.78005818e-01, 4.91095684e+03, 2.55795385e+00, -9.69857512e-02]
y_std : [7.61077821e-01, 8.42965361e-01, 4.97515564e+02, 1.15882902e+00, 3.06636238e-01]

object_name: 'StarNet_cls'

resume_from : 'D:/Notebook_workdir/thesis/model_save/StarNet_cls/best.pth'

lr: 0.001

model:
  name: 'StarNet'
  len_spectrum: 4900

loss: 
  cls_loss:
    loss_name: 'CrossEntropyLoss'
    rate: 1

scheduler:
  name: 'StepLR'
  step_size: 30
  gamma: 0.75
